#!/bin/bash

# nfc-read: Reads an NFC chip and outputs JUST the ID
#
# MakeICT/Bluebird Arthouse Electronic Door Entry
#
# Dominic Canare <dom@greenlightgo.org>
# Rye Kennedy <ryekennedy@gmail.com>

nfc-poll | grep UID | tr -d " "  | cut -d ":" -f 2

exit $?

