#!/bin/bash

# MakeICT/Bluebird Arthouse Electronic Door Ebtrt
# Dominic Canare <dom@greenlightgo.org>
# Rye Kennedy <ryekennedy@gmail.com>

nfc-poll | grep UID | tr -d " "  | cut -d ":" -f 2

exit $?

