"""empty message

Revision ID: 091a3b13552f
Revises: 7878dd192b50
Create Date: 2019-07-25 20:42:34.336206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091a3b13552f'
down_revision = '7878dd192b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('join_date')

    # ### end Alembic commands ###
